server:
  port: 9000

spring:
  application:
    name: demo

  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/dior?autoReconnect=true&serverTimezone=UTC #jdbc:mysql://54.151.127.182/dior?autoReconnect=true # 변경해주세요 #&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false
    username: h
    password: Comgong!2022
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql 8버전
    # driver-class-name: com.mysql.jdbc.Driver # mysql 5버전
